### ISSUE TITLE
No Migrations?

### ISSUE THREAD

**Issue by kacey90** [kgrzybek/modular-monolith-with-ddd#2]
I find this architecture very nice, especially because of its complexity and the modular approach you adopted. However, I noticed that there are no migrations that creates the DB models from the domain. I have read somewhere that code first migrations bring a lot of issues in enterprise level development especially in production. I feel it's why you probably didn't use it. 
I see you have a database project. Does this mean I'll have to create the database and still code the domain models too? Please I need you to throw more light on this.

**Comment by kgrzybek** [comment]
Thank your for that great question @kacey90 

In my opinion the best way to manage database changes is using both approaches - **versioning state** and **versioning transitions**. I wrote about this 2 articles on my blog:

http://www.kamilgrzybek.com/database/database-change-management/

http://www.kamilgrzybek.com/database/using-database-project-and-dbup-for-database-management/

As you can read from second linked post I use DbUp library and raw migration scripts to create transitions. I don't use EF migrations because I want to have full control on what is applied to my database. I have not added DbUp to this repository yet because it was first release but I definitely have plan to do that :)

**Comment by kacey90** [comment]
@kgrzybek Thank you for your response. I'll read the articles and try to apply them myself. Many thanks again.

**Comment by kacey90** [comment]
Sorry that I have to reopen this. I'm trying to use DbUp to handle migrations on the project. But I'm unable to use Migrations to generate the script using "Script-Migration" on Visual Studio or dotnet ef "dotnet ef migrations script" on CLI.
When I tried running the command on the UserAccess.Infrastructure module, It throws the following error;

> Unable to create an object of type 'UserAccessContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728

I included the -verbose parameter in the command for more details and got this;

> System.MissingMethodException: No parameterless constructor defined for type 'IGRMgr.Modules.UserAccess.Infrastructure.UserAccessContext'.

The DbContext seems pretty fine to me. Why wouldn't it work?

**Comment by kgrzybek** [comment]
In my implementation UserAccessContext does not have parameterless constructor, only this:
```csharp

public UserAccessContext(DbContextOptions options, ILoggerFactory loggerFactory) : base(options)
{
    _loggerFactory = loggerFactory;
}

So what I understand from the error message, you need to add parameterless constructor to support EF Migrations.

**Comment by kacey90** [comment]
Yes I noticed. And I tried the parameterless constructor but EF couldn't find the dbContextOptions as a result and threw the following error

> No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
