### ISSUE TITLE
Can we be best friends?

### ISSUE THREAD

**Issue by codyclay88** [kgrzybek/modular-monolith-with-ddd#36]
I want you know how much this has helped tie up several loose ends in my understanding of concepts like Entities, ValueObjects, CQRS, Modular Monolith, while also pulling together technologies like EF Core, Mediator, ASP.NET Core, Serilog, Quartz.NET, all into one project.

Thank you for this and I look forward to learning more from you and from this project in the future!

**Comment by kgrzybek** [comment]
Hi @codyclay88 

Thanks! Such comments are for me the best payment and motivation for continuous development!

**Comment by matieux** [comment]
I also want to add my acknowledgement: It clarified a lot of DDD implementation details for me as well. Finally a great DDD production-ready example with a modern stack! On a personal note, I have been a Unix guy since 20 years... and your project convinced me to do the jump to the .Net Core ecosystem.

I'm currently reading _Hands-On Domain-DrivenDesign with .NET Core_. This is a good book, but I would definitely recommend your implementation of the DDD Tactictal patterns over the code examples from the book. OK, to be fair, these book examples were written mostly for education purpose, not production.

I would be curious to know if you have some roadmap for this project or if you think it's mostly complete. Some ideas: different deployment options (DBs, etc), example about how to break the monolith for one service that needs to scale.

Cheers

**Comment by kgrzybek** [comment]
Hi @matieux, thank you very much for what you wrote! I am very happy that you jumped in .NET Core platform and this project was some kind of motivation of that 😲 

I have read Alexey Zimarev book and I like it too. I like that he shows a different approach using EventSourcing for example. Nevertheless, this project implementation is more similar to what Evans and Vernon presented in their books.

About roadmap - it is not specified, but currently, 2 things are planned in the near future:
1. More advanced Payments module implementation with Event Sourcing, maybe even 2 implementations in 2 different databases
2. Patterns catalog - I want to describe all patterns used in this project
