### ISSUE TITLE
Creating of MeetingGroupProposal not works

### ISSUE THREAD

**Issue by denis-tsv** [kgrzybek/modular-monolith-with-ddd#48]
Administration module contains command RequestMeetingGroupProposalVerificationCommand which inherits InternalCommandBase<Guid> and implements ICommand<TResult>

But ProcessInternalCommandsCommandHandler converts deserialized command to ICommand, so commandToProcess is null. RequestMeetingGroupProposalVerificationCommand deserialized again and again in infinite loop because it not processed and ProcessedDate is null.
I think it is possible to create additional field Attempts at InternalCommand, wrap execution of command in try/catch and increase attempts in catch block. If Attempts exceed some limit (for example, 3 attempts) then we will select it for execution next time.

Also we can replace code JsonConvert.DeserializeObject(internalCommand.Data, type) as ICommand by (ICommand)JsonConvert.DeserializeObject(internalCommand.Data, type). In this case we will receive not NRE but more informative InvalidCastException.

And we can create a naming convention for all internal commands and create an architecture test which check this convention. For example all classes which name ends with InternalCommand must implement interface ICommand

**Comment by kgrzybek** [comment]
Thanks @denis-tsv 

Yes, as I wrote in another issue - it was a bug introduced during integration tests implementation. I changed the internal command to return value during processing and forgot to change `ProcessInternalCommandsCommandHandler`. The fix is to remove casting to ICommand and use `dynamic` keyword - now it works as earlier with void result.

See the change, please:

https://github.com/kgrzybek/modular-monolith-with-ddd/commit/4f66e8a558e75bb2e62687f939f2b74c65d65537#diff-84877ec16265e4c62a39f8b550aa5e0a
