### ISSUE TITLE
[Question] Is there any rule guards against duplicated meetings?

### ISSUE THREAD

**Issue by dario-l** [kgrzybek/modular-monolith-with-ddd#5]
Is there any rule guards against duplicated meetings or any other example of domain validation that spans multiple aggregates:
- meeting with the same title on the same time
- duplicated user login
- etc...?

**Comment by kgrzybek** [comment]
Good timing Darek, I am working on this right now (second iteration 😄) together with implementation of unit tests for Domain Models.

I just published new commit with one scenario which you described (user login duplication):

Business rule:
```csharp
public class UserLoginMustBeUniqueRule : IBusinessRule
{
    private readonly IUsersCounter _usersCounter;
    private readonly string _login;

    internal UserLoginMustBeUniqueRule(IUsersCounter usersCounter, string login)
    {
        _usersCounter = usersCounter;
        _login = login;
    }

    public bool IsBroken() => _usersCounter.CountUsersWithLogin(_login) > 0;

    public string Message => "User Login must be unique";
}
```
Implementation of DomainService:
```csharp
public class UsersCounter : IUsersCounter
{
    private readonly ISqlConnectionFactory _sqlConnectionFactory;

    public UsersCounter(ISqlConnectionFactory sqlConnectionFactory)
    {
        _sqlConnectionFactory = sqlConnectionFactory;
    }

    public int CountUsersWithLogin(string login)
    {
        var connection = _sqlConnectionFactory.GetOpenConnection();

        const string sql = "SELECT " +
                           "COUNT(*) " +
                           "FROM [users].[v_Users] AS [User]" +
                           "WHERE [User].[Login] = @Login";
        return connection.QuerySingle<int>(sql,
            new
            {
                login
            });
    }
}
```

Unit test:
```csharp
[Test]
public void NewUserRegistration_WithoutUniqueLogin_BreaksUserLoginMustBeUniqueRule()
{
    var usersCounter = Substitute.For<IUsersCounter>();

    usersCounter.CountUsersWithLogin("login").Returns(x => 1);

    AssertBrokenRule<UserLoginMustBeUniqueRule>(() =>
    {
        UserRegistration.RegisterNewUser(
            "login", "password", "test@email",
            "firstName", "lastName", usersCounter);
    });
}
```

As you can see in this case I'm using Method Injection which is my preferred approach to validate rules that spans multiple aggregates. 

Other common scenario is already implemented here:

```csharp
internal class MeetingAttendeeMustBeAMemberOfGroupRule : IBusinessRule
{
    private readonly MeetingGroup _meetingGroup;

    private readonly MemberId _attendeeId;
    internal MeetingAttendeeMustBeAMemberOfGroupRule(MemberId attendeeId, MeetingGroup meetingGroup)
    {
        _attendeeId = attendeeId;
        _meetingGroup = meetingGroup;
    }

    public bool IsBroken()
    {
        return !_meetingGroup.IsMemberOfGroup(_attendeeId);
    }

    public string Message => "Meeting attendee must be a member of group";
}
```

This ``MeetingGroup`` is provided by CommandHandler only for validation purposes, because ``Meeting`` doesn't have reference to ``MeetingGroup`` (and of course it shouldn't have!).

Both approaches have pros and cons - depending on requirements, performance issues, number of items, eventual consistency and more but this is another topic.

**Comment by kacey90** [comment]
I commend your efforts on this project Kamil. But do you think it's okay to have a separate asp.net core mvc project to take of authentication alone with IdentityServer and asp.net identity. The UserAccess module can then let that project handle the registration and save the login information on its own domain if the action is successful. What do you think about this approach?

**Comment by dario-l** [comment]
@kgrzybek 

That's great Kamil. Thanks :)

**Comment by kgrzybek** [comment]
@kacey90 - please create new issue because this question is not related with this topic :)

@dario-l You are welcome! I am closing the issue.
