### ISSUE TITLE
Infrastructure Service - Design

### ISSUE THREAD

**Issue by jgozner** [kgrzybek/modular-monolith-with-ddd#53]
I have another design question 😃 

I wanted to understand how you would integrate a service such as AWS S3 into this domain. Let's say that we allow users to upload files/images to meetings for people to access. This could be images of meeting venue so people could see it before hand. (Business Rule) Meetings are allowed to have a max of 10 images. (I could give more examples but I think this works.)

The FileService would have the following functionality:
- creating signed urls
- renaming files
- moving files
- deleting files
- getting file metadata (maybe we could use this info to validate the upload images?)

I'm thinking you could abstract the AWS S3 functionality into a FileService.

MyMeetings.BuildingBlocks.Infrastructure
----------------------------------------------FilesService/ 
----------------------------------------------------------- IFileService
----------------------------------------------------------- FileService (FileConfiguration)
----------------------------------------------------------- FileConfiguration (bucketName, region, keys)

MyMeetings.Meetings.Module.Infrastructure
-------------------------------------------------FileService/
-------------------------------------------------------------FileModule (FileService, FileConfiguration)

Then within the Meetings.Module.Application we would use this service and update the appropriate aggregates. 

I just wanted to thank you again for such an amazing repo. I've been learning so much.

**Comment by kgrzybek** [comment]
When I saw your issue I noticed one design smell in my solution.`IEmailSender` interface was defined in BuildingBlocks.Infrastructure and it was not a good choice.

According to OOD/SOLID principles, the interface should be placed next to the client of this interface, so it should be placed in BuildingBlocks.Application layer, because this layer requires this interface. Infrastructure should only contain implementation of this interface. I changed this.

Back to your question now considering what I wrote above:
1. If only one module needs to use integrate with AWS you should put interfaces and implementations only in that module. In BuildingBlocks put only necessary, common things.
2. In Modules.Meetings.Application define IFileService
3. In Modules.Meetings.Infrastructure define something like AWSFileService which implements IFileService. See the naming - in the Application interface, there is no information about concrete implementation (abstraction). In Infrastructure there is information because this is concrete implementation as DI says:

> High-level modules should not depend on low-level modules. Both should depend on abstractions (e.g. interfaces).
> Abstractions should not depend on details. Details (concrete implementations) should depend on abstractions.
