### ISSUE TITLE
How many times should UnitOfWorkCommandHandler(WithResult)Decorator fire?

### ISSUE THREAD

**Issue by trevorchunestudy** [kgrzybek/modular-monolith-with-ddd#56]
Hi. Great project!  You have literally distilled Eric Evans (and others) blue book into a real (non-trivial and complete) project.

I am not sure if this is an issue but stepping through the code I noticed on (for example) CreateUserTests.CreateUser_Test.RegisterNewUserCommand, the decorator(s) fire more than once.  Is this expected behavior?  The reason I ask is that I haven't been able to follow those UoW "side effect" registrations in the MediatorModule(s) and ProcessingModule(s).  I can't even reason why they are firing at all as most of the pre/post registrations I have seen documented elsewhere are different(I think).

Could I please ask for a small explanation of how you accomplished this?  Thanks again.

**Comment by kgrzybek** [comment]
Hi @trevorchunestudy,

Logging, Validation and UnitOfWork Decorator should fire only once for particular command handling. I checked CreateUserTests.CreateUser_Test.RegisterNewUserCommand and they work correctly. Do you have a different behavior? 

The only decorator that can run several times when processing one command is DomainEventsDispatcherNotificationHandlerDecorator because events can be published from different aggregates (reactively). For example Command ->CommandHandler -> method on Aggregate -> Event1 -> Event1Handler-> execute different method on the same or different  Aggregate -> Event2 -> Event2Handler....etc.

**Comment by trevorchunestudy** [comment]
Hi @kgrzybek ,

When I find a really good project that has been well thought out, I like to take it apart and put it back together.  I think I had a few extras pieces of the motorcycle on the garage floor.  I re-cloned a fresh copy of the repo and indeed those handlers were behaving as expected.  Sorry for the trouble.

Are all of the configurations for registering those types of decorators located in Mediator & Processing modules(.cs) respectively?  I think the 'rebuilt' version I have been working on is missing something because I either have those decorators firing more than once or not at all.  Clearly something wrong on my end.

Thanks again for all the time you spent on this.  I stumbled onto this repo via research into Event Storming actually and I was amazed at how well that exercise (using DDD principles) translated almost in a 'color by numbers' way to this repo.
