### ISSUE TITLE
FrontEnd SPA application

### ISSUE THREAD

**Issue by iang0ld** [kgrzybek/modular-monolith-with-ddd#59]
I noticed this in the Roadmap. Has anybody down this? How far away would one be?

**Comment by kgrzybek** [comment]
Hi @iang0ld,

Yes, it is in the Roadmap but I have not started yet. 

However, I started to wonder if anyone would like to do something like that. It sounds simple but still requires some effort and time.

**Comment by szenadam** [comment]
@kgrzybek What kind of framework would you like to have as your SPA frontend?
Angular? React? Vue? Or some other kind?

**Comment by kgrzybek** [comment]
@szenadam It can be any of these 3. Any help will be really, really useful.

**Comment by igor-toporet** [comment]
Angular is dead, let's showcase one of Top-3: React, Vue or Svelte.
https://2019.stateofjs.com/front-end-frameworks/

**Comment by iang0ld** [comment]
I vote for Vue with nswag.  I feel Svelte is too new. Not enough tools and community for a serious project.  Personally I much prefer HTML to JSX, and I think Vue improves React by introducing some of the good things from Angular. Maby I'm a bit BIAS :)

**Comment by MarkGravestock** [comment]
I'm interested to understand if there has been any discussion/thought around the structure of the front end UI, as well as possible technologies to implement? 
I'm thinking specifically how the UI relates to the existing bounded contexts, how should it align with those and how should it be designed so that it is modular in line with those, maybe with a thin composition layer (e.g. [composite UI](https://www.jamesmichaelhickey.com/microservices-architecture/))? 
Is it possible it needs its own bounded context or contexts? There was an interesting discussion in the [virtual ddd community](https://www.youtube.com/embed/wMX9PdRYuRo) which I understood to be about whether the users may need a seperate model/bounded context to those created wiht domain experts, that is their view may be a simplfied view of the internal bounded contexts. I think this is probably not be the case here, as the domain models of the bounded contexts align with the users view and would probably be revealed during event storming, etc..

**Comment by Lobosque** [comment]
I would also consider Blazor as means to showcase the .NET stack

**Comment by kgrzybek** [comment]
Due to the lack of interest in this topic by others, some time ago I decided to implement SPA application using the **React** library. The first, very beta version is almost ready and will be released soon. 

Of course, I invite you to contribute because there will be a lot of work to do.

**Comment by radian7** [comment]
I propose also Blazor :).

**Comment by kgrzybek** [comment]
As I wrote I published a week ago the first version of FrontEnd application in React: https://github.com/kgrzybek/modular-monolith-with-ddd-fe-react 

Once again, I invite you to contribute.
