### ISSUE TITLE
Consider behaviors instead of decorators for cross-cutting concerns

### ISSUE THREAD

**Issue by jsantha** [kgrzybek/modular-monolith-with-ddd#64]
MediatR offers first class support for extending command processing pipeline with own behaviors. It feels more natural to implement cross-cutting this way (in oppose to decorators).

https://github.com/jbogard/MediatR/wiki/Behaviors

If I'm not missing something then whole pipeline (logging, validation, UoW) can be migrated to behaviors. At the same time we can avoid some DI shenanigans that can be unreliable in other containers.

**Comment by kgrzybek** [comment]
Hi @jsantha,

Yes, you can use MediatR behaviors to implement Chain Of Responsibility pattern instead of using decorators.

Honestly, I used MediatR behaviors some time ago but finally, I switched to IoC decorators. The main reason was that I wanted to decrease coupling to MediatR library, I even wanted to remove this coupling at all and implement Mediator pattern from scratch. I have not done it yet, but still I feel that usage of decorators is more cleaner solution, but I understand that someone can think opposite.

Finally, I think it is a matter of choice and both solutions are very similar and good.
