### ISSUE TITLE
Events in Entities, not in AggregateRoots

### ISSUE THREAD

**Issue by rmaziarka** [kgrzybek/modular-monolith-with-ddd#7]
Hello Kamil,

I have a question regarding domain events. In some sources, which I used as my knowledge base (like [this](http://danielwhittaker.me/2014/11/15/aggregate-root-cqrs-event-sourcing/)), there was information to store events in Aggreagates Roots. I see that in your code [Entity](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/BuildingBlocks/Domain/Entity.cs) contains such code and we add events in entities as well - [MeetingAttendee](https://github.com/kgrzybek/modular-monolith-with-ddd/blob/master/src/Modules/Meetings/Domain/Meetings/MeetingAttendee.cs).

What was the reason behind that decision? It is not that I am thinking that this is wrong - I am just curious. I thought we would like to allow and store changes only in AggregateRoot.

**Comment by kgrzybek** [comment]
Hi Radek,

Great question, I'm glad I can answer.

Short answer: **store events in Entities**

Long answer:
1. Please see [DDD reference](http://domainlanguage.com/wp-content/uploads/2016/05/DDD_Reference_2015-03.pdf) and page vii (Pattern Language Overview). In diagram there is explicit connection: ENTITIES - push state change with -> DOMAIN EVENTS
2. In Vaughn's Vernon DDD Distilled Book is described that Domain Events are side effects of  operation invoked on **Aggregate**.  ``AggregateRoot`` is not mentioned.

So it is important to be very strict in naming. 
**AggegateRoot is Entity. It is not Aggregate. Aggregate and AggregateRoot has the same name, but they are different things.** 

``Domain Events`` are related to ``Aggregates`` through ``Entities``. 

Storing all events only in ``AggregateRoot`` is possible, but in my opinion inefficient and can cause that you would have most logic in ``AggregateRoot``. This is bad, because you should have logic as close as possible to entity which is related to this ``Domain Event`` - to not violate "Law Of Demeter"/"Tell don't ask principle" and avoid anemic entities.

**Comment by rmaziarka** [comment]
Thanks, that's a good explanation 😊
